import { Difficulty } from 'scan-chart';
import { ALL_DIFFICULTIES } from '../../../constants';
import { Song, SongLessonInfo } from '../../../types';
import { calculateAccuracy, getStarRating } from '../../scoring';
import { LESSON_CLEAR_ACCURACY } from '../../services/lesson-progression';

/**
 * Lesson songs generated by the SightKick Method curriculum live in
 * folders/names prefixed with this string. `sk_lesson_id` (see
 * `isLessonSong` below) is the authoritative signal — this prefix is a
 * defensive fallback for lesson songs whose ini fields haven't landed yet
 * (or got stripped) but are still clearly part of the method.
 */
export const LESSON_NAME_PREFIX = 'SightKick Method - ';

/**
 * Presentation-only rebrand: the app now shows the curriculum as "Drumroll
 * Method" in the UI, but the on-disk folder/name prefix above, the `sk_*`
 * ini fields, and the isLessonSong() prefix fallback all still match
 * "SightKick Method - " so existing libraries keep scanning correctly. Use
 * this constant for anything the user reads; never for matching data.
 */
export const LESSON_METHOD_DISPLAY_NAME = 'Drumroll Method';

function basename(dir: string): string {
  const segments = dir.split(/[\\/]/).filter(Boolean);

  return segments[segments.length - 1] ?? '';
}

export function isLessonSong(song: Song): boolean {
  if (song.lesson) {
    return true;
  }

  return (
    song.name.startsWith(LESSON_NAME_PREFIX) ||
    basename(song.dir).startsWith(LESSON_NAME_PREFIX)
  );
}

/**
 * True when the library contains songs that look like part of the
 * SightKick Method curriculum (folder/name prefix match) but don't carry
 * parsed lesson data. This is the stale-schema signature: the store's
 * `toSong()` snapshot for these songs was captured by an older build whose
 * parser didn't extract the `sk_lesson_*` ini fields, so `song.lesson` is
 * missing even though the song clearly belongs to the curriculum. A fresh
 * rescan re-parses `song.ini` and fixes it — see `useLessonAutoRescan`.
 */
export function hasUnparsedLessonSongs(songList: Song[]): boolean {
  return songList.some(
    (song) =>
      !song.lesson &&
      (song.name.startsWith(LESSON_NAME_PREFIX) ||
        basename(song.dir).startsWith(LESSON_NAME_PREFIX)),
  );
}

/**
 * Lesson charts ship only an Expert drum track. Opening a lesson must use
 * whatever difficulty is actually charted for it — not the app's globally
 * selected difficulty tab, which may be Easy/Medium/Hard and would land on
 * a track the lesson never charted. Picks the highest charted difficulty
 * (in practice, always Expert for lessons); undefined if none is charted.
 */
export function highestAvailableDifficulty(song: Song): Difficulty | undefined {
  const available = song.drumDifficulties;

  if (!available || available.length === 0) {
    return undefined;
  }

  return [...ALL_DIFFICULTIES].reverse().find((d) => available.includes(d));
}

/** Best star rating (0-5) earned on a song across every played difficulty. */
export function bestStarsForSong(song: Song): number {
  if (!song.scoreData) {
    return 0;
  }

  return ALL_DIFFICULTIES.reduce((best, difficulty) => {
    const data = song.scoreData?.[difficulty];

    return data ? Math.max(best, getStarRating(data)) : best;
  }, 0);
}

/** Best scored accuracy (0-1) on a lesson across every played difficulty. */
export function bestAccuracyForSong(song: Song): number {
  if (!song.scoreData) {
    return 0;
  }

  return ALL_DIFFICULTIES.reduce((best, difficulty) => {
    const data = song.scoreData?.[difficulty];

    return data ? Math.max(best, calculateAccuracy(data)) : best;
  }, 0);
}

/** A clear is one saved complete learning pass at the adaptive clear gate. */
export function isLessonCleared(song: Song): boolean {
  return (
    isLessonSong(song) && bestAccuracyForSong(song) >= LESSON_CLEAR_ACCURACY
  );
}

export interface LessonEntry {
  song: Song;
  lesson: SongLessonInfo;
  /** Best star rating earned on this lesson, any difficulty. */
  bestStars: number;
  /** True after a saved full learning pass met the adaptive clear gate. */
  cleared: boolean;
  unlocked: boolean;
  /** 0 when unlocked, otherwise prior lesson clears still needed. */
  clearsNeeded: number;
}

export interface LessonUnitGroup {
  unit: string;
  entries: LessonEntry[];
}

export interface LessonProgress {
  /** All lesson entries, ordered by sk_stars_to_unlock ascending. */
  entries: LessonEntry[];
  /** Entries grouped by sk_unit, in chain order. */
  groups: LessonUnitGroup[];
  totalLessons: number;
  unlockedCount: number;
  /** Total stars earned across every lesson song, any difficulty. */
  totalStars: number;
  /** Count of lessons cleared at the adaptive learning gate. */
  clearedCount: number;
  /** Furthest unlocked lesson that has not yet been cleared. */
  continueEntry?: LessonEntry;
  /** Furthest-reached locked lesson, shown when everything unlocked is cleared. */
  nextLockedEntry?: LessonEntry;
}

const EMPTY_PROGRESS: LessonProgress = {
  entries: [],
  groups: [],
  totalLessons: 0,
  unlockedCount: 0,
  totalStars: 0,
  clearedCount: 0,
  continueEntry: undefined,
  nextLockedEntry: undefined,
};

function authoredLessonRichness(
  song: Song & { lesson: SongLessonInfo },
): number {
  const lesson = song.lesson;

  return [
    lesson.skills?.length,
    lesson.prerequisiteIds?.length,
    lesson.targetLanes?.length,
    lesson.bpmStart,
    lesson.bpmTarget,
    lesson.doseRule,
    lesson.masteryRule,
    lesson.cue,
    lesson.assessmentBoundary,
  ].filter(Boolean).length;
}

/**
 * Bootstrap owns the durable migration, but imported or interrupted legacy
 * profiles can still briefly contain two rows for one lesson ID. Journey must
 * never double-count their stars or render duplicate nodes. Prefer the richer
 * authored kb.2 record; on an exact metadata tie, retain the record with the
 * stronger earned result.
 */
function uniqueLessonSongs(
  songList: Song[],
): Array<Song & { lesson: SongLessonInfo }> {
  const byLessonId = new Map<string, Song & { lesson: SongLessonInfo }>();

  for (const song of songList) {
    if (!isLessonSong(song) || !song.lesson) {
      continue;
    }

    const lessonSong = song as Song & { lesson: SongLessonInfo };
    const previous = byLessonId.get(lessonSong.lesson.id);

    if (
      !previous ||
      authoredLessonRichness(lessonSong) > authoredLessonRichness(previous) ||
      (authoredLessonRichness(lessonSong) ===
        authoredLessonRichness(previous) &&
        bestStarsForSong(lessonSong) > bestStarsForSong(previous))
    ) {
      byLessonId.set(lessonSong.lesson.id, lessonSong);
    }
  }

  return [...byLessonId.values()];
}

/**
 * Computes the Lessons unlock chain from the full song library.
 *
 * Unlock rule: the legacy `sk_stars_to_unlock` number is the authored chain
 * position (0, 1, 2, ...). One honest complete learning clear contributes one
 * curriculum credit, so a high star rating can never skip several lessons.
 * The first lesson remains available because its authored threshold is 0.
 */
export function computeLessonProgress(songList: Song[]): LessonProgress {
  const lessonSongs = uniqueLessonSongs(songList);

  if (lessonSongs.length === 0) {
    return EMPTY_PROGRESS;
  }

  const totalStars = lessonSongs.reduce(
    (sum, song) => sum + bestStarsForSong(song),
    0,
  );
  const clearedCount = lessonSongs.filter(isLessonCleared).length;
  const entries: LessonEntry[] = lessonSongs
    .map((song) => {
      const bestStars = bestStarsForSong(song);
      const cleared = isLessonCleared(song);
      const unlocked = clearedCount >= song.lesson.starsToUnlock;

      return {
        song,
        lesson: song.lesson,
        bestStars,
        cleared,
        unlocked,
        clearsNeeded: unlocked ? 0 : song.lesson.starsToUnlock - clearedCount,
      };
    })
    .sort((a, b) => a.lesson.starsToUnlock - b.lesson.starsToUnlock);
  const groups: LessonUnitGroup[] = [];
  const groupByUnit = new Map<string, LessonUnitGroup>();

  for (const entry of entries) {
    const key = entry.lesson.unit || 'Lessons';
    let group = groupByUnit.get(key);

    if (!group) {
      group = { unit: key, entries: [] };
      groupByUnit.set(key, group);
      groups.push(group);
    }

    group.entries.push(entry);
  }

  const eligibleContinue = entries.filter(
    (entry) => entry.unlocked && !entry.cleared,
  );
  const continueEntry = eligibleContinue[eligibleContinue.length - 1];
  const nextLockedEntry = entries.find((entry) => !entry.unlocked);

  return {
    entries,
    groups,
    totalLessons: entries.length,
    unlockedCount: entries.filter((entry) => entry.unlocked).length,
    totalStars,
    clearedCount,
    continueEntry,
    nextLockedEntry,
  };
}

export function lockedHint(entry: LessonEntry): string {
  return `Clear ${entry.clearsNeeded} more lesson${
    entry.clearsNeeded === 1 ? '' : 's'
  }`;
}
