import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { parseChartFile } from 'scan-chart';
import { describe, expect, it } from 'vitest';
import { ChartParser } from '../../../chart-parser/parser';
import { parseStickingData } from '../sticking';
import { mapVocalizationTrack } from './mapper';
import { synthesizePlaceholderBank } from './placeholder';
import { renderVocalizationTrack } from './render';

const lessonDirectory = path.resolve(
  'web/public/library/SightKick Method - Lesson 11.04 - Two-Bar Fill Idea',
);
const artifactDirectory = path.resolve('tmp/lanes/m-demo');

describe('real lesson vocalization demo', () => {
  // web/public/library is generated by `yarn package:lesson-library` and is
  // absent on CI checkouts — same boundary as forbidden-copy.test.ts.
  it.skipIf(!existsSync(lessonDirectory))(
    'renders lesson 11.04 from its shipped chart and sticking data',
    () => {
      const midi = readFileSync(path.join(lessonDirectory, 'notes.mid'));
      const chart = parseChartFile(new Uint8Array(midi), 'mid', {
        pro_drums: true,
        five_lane_drums: false,
      });
      const parser = new ChartParser(chart, false, 'expert');
      const sticking = parseStickingData(
        JSON.parse(
          readFileSync(path.join(lessonDirectory, 'sticking.json'), 'utf8'),
        ),
      );

      expect(sticking).toBeDefined();

      const track = mapVocalizationTrack({
        chart,
        measures: parser.measures,
        sticking,
      });
      const rendered = renderVocalizationTrack(
        track,
        synthesizePlaceholderBank(),
      );
      const counts = Object.fromEntries(
        [...new Set(track.events.map((event) => event.sampleId))].map(
          (sampleId) => [
            sampleId,
            track.events.filter((event) => event.sampleId === sampleId).length,
          ],
        ),
      );

      if (process.env.DRUMROLL_WRITE_VOCALIZATION_DEMO === '1') {
        writeFileSync(
          path.join(artifactDirectory, 'lesson-11.04-rhythm-voice.wav'),
          rendered.wavBytes,
        );
        writeFileSync(
          path.join(artifactDirectory, 'lesson-11.04-rhythm-voice.json'),
          `${JSON.stringify(
            {
              lesson: '11.04 — Two-Bar Fill Idea',
              source: path.relative(process.cwd(), lessonDirectory),
              durationSeconds: track.durationSeconds,
              eventCount: track.events.length,
              sampleCounts: counts,
              sequence: track.events.map((event) => ({
                timeSeconds: Number(event.timeSeconds.toFixed(4)),
                tick: event.tick,
                syllable: event.syllable,
                sampleId: event.sampleId,
                dynamic: event.dynamic,
                limb: event.limb,
              })),
            },
            null,
            2,
          )}\n`,
        );
      }

      expect(track.events.length).toBeGreaterThan(50);
      expect(counts.snare_accent_bak).toBeGreaterThan(0);
      expect(counts.snare_ghost_ki).toBeGreaterThan(0);
      expect(counts.tom_high_tim).toBeGreaterThan(0);
      expect(counts.crash_kshh_long).toBeGreaterThan(0);
      expect(rendered.wavBytes.byteLength).toBeGreaterThan(100000);
    },
  );
});
