import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { extname, relative, resolve, sep } from 'node:path';
import ts from 'typescript';
import { describe, expect, it } from 'vitest';

const root = resolve(process.cwd());
const textExtensions = new Set([
  '.css',
  '.html',
  '.json',
  '.md',
  '.mjs',
  '.py',
  '.sh',
  '.toml',
  '.ts',
  '.tsx',
  '.txt',
  '.yaml',
  '.yml',
]);
const excludedParts = new Set(['docs', 'test', 'tests', 'tmp', '__tests__']);
const forbiddenCopy = /support\s+(?:the\s+)?project/i;
const forbiddenBrandCopy = /\bSightKick\b(?! Method)/;
const forbiddenFillerCopy =
  /\b(?:simply|seamlessly|robust|powerful|comprehensive|leverage|effortlessly)\b/i;
const forbiddenHedgingCopy = /\b(?:could|may|might|should)\b/i;
const copyRuleDeclaration = /^Do not use (?:filler|hedging modals):/;

function isExcluded(path: string) {
  const parts = relative(root, path).split(sep);
  const name = parts.at(-1) ?? '';

  return (
    parts.some((part) => excludedParts.has(part)) ||
    /\.(?:test|spec|stories)\.[^.]+$/.test(name)
  );
}

function textFiles(path: string): string[] {
  if (isExcluded(path)) {
    return [];
  }

  return readdirSync(path, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = resolve(path, entry.name);

    if (isExcluded(entryPath)) {
      return [];
    }

    if (entry.isDirectory()) {
      return textFiles(entryPath);
    }

    return textExtensions.has(extname(entry.name)) ? [entryPath] : [];
  });
}

function sourceStrings(path: string): string[] {
  const source = readFileSync(path, 'utf8');
  const sourceFile = ts.createSourceFile(
    path,
    source,
    ts.ScriptTarget.Latest,
    true,
    path.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
  );
  const strings: string[] = [];
  const visit = (node: ts.Node) => {
    if (
      ts.isStringLiteral(node) ||
      ts.isNoSubstitutionTemplateLiteral(node) ||
      ts.isJsxText(node)
    ) {
      strings.push(node.text);
    } else if (ts.isTemplateExpression(node)) {
      strings.push(node.getText(sourceFile));
    }

    ts.forEachChild(node, visit);
  };

  visit(sourceFile);

  return strings;
}

function curriculumCues(path: string): string[] {
  const lines = readFileSync(path, 'utf8').split('\n');
  const cues: string[] = [];

  for (let index = 0; index < lines.length; index += 1) {
    const match = /^(\s*)cue:\s*(.*)$/.exec(lines[index]);

    if (!match) {
      continue;
    }

    const indent = match[1].length;
    const parts = [match[2].trim()];

    while (index + 1 < lines.length) {
      const next = lines[index + 1];
      const nextIndent = next.length - next.trimStart().length;

      if (next.trim() && nextIndent <= indent) {
        break;
      }

      index += 1;

      if (next.trim()) {
        parts.push(next.trim());
      }
    }

    cues.push(parts.filter(Boolean).join(' '));
  }

  return cues;
}

function hasProseSemicolon(copy: string): boolean {
  const normalized = copy
    .replace(/&(?:amp|apos|gt|lt|quot|#\d+);/g, '')
    .replace(/\$\{[^{}]*\}/g, 'value');

  if (
    normalized.includes('<style') ||
    normalized.includes('<!doctype') ||
    /\.[\w-]+[^\n{]*\{/.test(normalized)
  ) {
    return false;
  }

  return /[A-Za-z0-9)];\s+[A-Za-z]/.test(normalized);
}

describe('forbidden user-facing copy', () => {
  it('never ships old branding or project-support language in user-facing text', () => {
    // web/public/library is generated by `yarn package:lesson-library`; it is
    // absent on CI checkouts, where only the tracked roots can be scanned.
    // Local runs and the macOS release gates always have it and keep scanning.
    const scannedRoots = [
      resolve(root, 'src/renderer'),
      resolve(root, 'resources'),
      resolve(root, 'web/public/library'),
    ].filter((path) => existsSync(path));
    const supportViolations = scannedRoots
      .flatMap(textFiles)
      .filter((path) => forbiddenCopy.test(readFileSync(path, 'utf8')))
      .map((path) => relative(root, path));
    const brandViolations = textFiles(resolve(root, 'src/renderer'))
      .filter((path) => forbiddenBrandCopy.test(readFileSync(path, 'utf8')))
      .map((path) => relative(root, path));

    expect([...supportViolations, ...brandViolations]).toEqual([]);
  });

  it('keeps renderer strings and lesson cues free of semicolons, filler, and hedging', () => {
    const sourceRoots = [
      resolve(root, 'src/renderer'),
      resolve(root, 'src/main/ai-tutor'),
    ];
    const sourceViolations = sourceRoots
      .flatMap(textFiles)
      .filter((path) => ['.ts', '.tsx'].includes(extname(path)))
      .flatMap((path) =>
        sourceStrings(path)
          .filter(
            (copy) =>
              !copyRuleDeclaration.test(copy) &&
              (hasProseSemicolon(copy) ||
                forbiddenFillerCopy.test(copy) ||
                forbiddenHedgingCopy.test(copy)),
          )
          .map((copy) => `${relative(root, path)}: ${copy}`),
      );
    const cueViolations = curriculumCues(
      resolve(root, 'resources/lessons/curriculum.yaml'),
    )
      .filter(
        (copy) =>
          copy.includes(';') ||
          forbiddenFillerCopy.test(copy) ||
          forbiddenHedgingCopy.test(copy),
      )
      .map((copy) => `resources/lessons/curriculum.yaml: ${copy}`);

    expect([...sourceViolations, ...cueViolations]).toEqual([]);
  });
});
